// This file is auto-generated by @hey-api/openapi-ts

/**
 * Field relative velocity
 */
export type FieldRelativeVelocity = {
    /**
     * Velocity in the x direction. Units: m/s
     */
    vx: number;
    /**
     * Velocity in the y direction. Units: m/s
     */
    vy: number;
    /**
     * Angular velocity. Units: rad/s
     */
    omega: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Response to a robot command
 */
export type RobotCommandResponse = {
    /**
     * Whether the command was successful or not
     */
    success: boolean;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type SetVelocityData = {
    body: FieldRelativeVelocity;
};

export type SetVelocityResponse = (RobotCommandResponse);

export type SetVelocityError = (HTTPValidationError);